export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const APP_LOAD = "APP_LOAD"
export const REDIRECT = "REDIRECT"
export const TOKEN_EXPIRED = "TOKEN_EXPIRED"
export const SETTINGS_SAVED = "SETTINGS_SAVED"
export const SERVER_STATUS = "SERVER IS DOWN FOR MAINTANANCE"